/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AppointmentStatus =
  | "ausente"
  | "cancelada"
  | "completada"
  | "confirmada"
  | "programada";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "dentist" | "patient" | "user";

export interface Appointments {
  appointmentDate: Timestamp;
  createdAt: Generated<Timestamp | null>;
  dentistId: number | null;
  durationMinutes: Generated<number | null>;
  id: Generated<number>;
  notes: string | null;
  patientId: number | null;
  reason: string | null;
  status: Generated<AppointmentStatus | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface ClinicalImages {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  fileName: string;
  fileUrl: string;
  id: Generated<number>;
  imageType: string | null;
  patientId: number | null;
  treatmentId: number | null;
  uploadedBy: number | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Patients {
  address: string | null;
  allergies: string | null;
  birthDate: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  emergencyContactName: string | null;
  emergencyContactPhone: string | null;
  id: Generated<number>;
  medicalHistory: string | null;
  phone: string | null;
  updatedAt: Generated<Timestamp | null>;
  userId: number | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Treatments {
  appointmentId: number | null;
  cost: Numeric | null;
  createdAt: Generated<Timestamp | null>;
  dentistId: number | null;
  description: string | null;
  id: Generated<number>;
  notes: string | null;
  patientId: number | null;
  status: Generated<string | null>;
  toothNumber: string | null;
  treatmentType: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  appointments: Appointments;
  clinicalImages: ClinicalImages;
  loginAttempts: LoginAttempts;
  patients: Patients;
  sessions: Sessions;
  treatments: Treatments;
  userPasswords: UserPasswords;
  users: Users;
}

// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = [
  "admin",
  "dentist",
  "patient",
  "user",
];
export const AppointmentStatusArrayValues: [AppointmentStatus, ...AppointmentStatus[]] = [
  "ausente",
  "cancelada",
  "completada",
  "confirmada",
  "programada",
];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
